blank_issues_enabled: true
contact_links:
  - name: "Report a Security Vulnerability or Risk"
    url: "https://github.com/mia-cx"
    about: "If you find a dangerous Security Vulnerability, please email us at security@mia.cx instead."