blank_issues_enabled: true
contact_links:
  - name: "Report a Security Vulnerability or Risk"
    url: "mailto:security@mia.cx"
    about: "If you find a dangerous Security Vulnerability, please email us in stead."